### ISSUE TITLE
How to extract svbench results as output files. 

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/svbench#2]
Hi, How can I extract results from svbench in a .txt file when running it in the command line in bash? Or do I need to use Python scripts? Currently, it displays all the results in the terminal instead of generating an output file. Thank you.

Please see an example attached to this message below.  
![Screenshot from 2024-01-30 14-10-55](https://github.com/kcleal/svbench/assets/45700858/544caf44-d603-410b-8c0e-86b1b2a69619)

![Screenshot from 2024-01-30 14-36-39](https://github.com/kcleal/svbench/assets/45700858/b9146738-98f5-4d2b-98da-020cf33d8762)

**Comment by kcleal** [comment]
Hi @poddarharsh15,
You will have to use the scripts I'm afraid. If you look at the `cli.py` file that will give you an idea of how to run the pipeline. The annotated data is found in a pandas DataFrame under `CallSet.breaks_df`. So to save a query callset use `dysgu_calls.breaks_df.to_csv('output.csv')'`. Or if you have a list of query datasets `pd.concat([q.breaks_df for q in query].to_csv('output.csv')]`
If you just want the data that is displayed to the terminal, I think you could use:

`svbench ref.vcf query.vcf 2> res.txt`

**Comment by poddarharsh15** [comment]
I am able to run everything in terminal using command, on other hand it's a bit complicated to collect all the data in a sheet to generate a graphical representation of multiple flowcells after benchmarking. I will try to use the python  scripts that you have suggested, Thanks again.
