### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by poddarharsh15** [kcleal/svbench#3]
Hi @kcleal I am encountering an error while benchmarking some datasets from HG002_CMRG. Could you please take a look at it?
Thank you for your assistance.

[HG002_GRCh38_INS.vcf.gz](https://github.com/kcleal/svbench/files/15484215/HG002_GRCh38_INS.vcf.gz)

`svbench --include ~/HG002_WGS_150/GRCh38/HG002_GRCh38_CMRG_SV_v1.00.bed  --pass-ref /home/tigem/h.poddar/HG002_WGS_150/GRCh38/HG002_GRCh38_INS.vcf.gz --pass-query delly_ins.vcf.gz  --min-size-ref 50 --slop 1000 --min-size-query 50 --pass-only`

> dataset=REFERENCE, caller=None, loaded rows: 58
columns: ['chrom', 'start', 'chrom2', 'end', 'svtype', 'w', 'id', 'size_filter_pass', 'svlen', 'filter', 'GT', 'FILTER']
n not in include: 0
Traceback (most recent call last):
  File "/home/tigem/h.poddar/anaconda3/bin/svbench", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/svbench/cli.py", line 27, in main
    filter_by_size(min_size_ref, None, keep_translocations=True)
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/svbench/io_tools.py", line 637, in filter_by_size
    size_filter = np.array([True if ((svlen >= min_s and svlen < max_s) or chrom1 != chrom2 or svlen is None or svlen != svlen) else False for svlen, chrom1, chrom2 in zip(df['svlen'], df['chrom'], df['chrom2'])])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/svbench/io_tools.py", line 637, in <listcomp>
    size_filter = np.array([True if ((svlen >= min_s and svlen < max_s) or chrom1 != chrom2 or svlen is None or svlen != svlen) else False for svlen, chrom1, chrom2 in zip(df['svlen'], df['chrom'], df['chrom2'])])
                                      ^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int
![Screenshot from 2024-05-29 14-20-06](https://github.com/kcleal/svbench/assets/45700858/e8f87ef8-8dc0-41a0-ab7b-b5744af0b624)

**Comment by kcleal** [comment]
No problem, I will take a look tomorrow

**Comment by poddarharsh15** [comment]
Hi @kcleal  thank you for answering :)

**Comment by kcleal** [comment]
Hi @poddarharsh15,
I think the error should be fixed now. You will need to install from source, rather than pypi. Could you confirm if its working your end? Thanks

**Comment by poddarharsh15** [comment]
Hi @kcleal I am trying to run the new version of SVBench installed from source, but I am encountering some parameter errors. Could you please take a look and provide some guidance on how to resolve these issues? 
I used the code mentioned below to install the newer version:- 

`git clone https://github.com/<username>/svbench.git
cd svbench
`
 

> 
> >  svbench --include ~/HG002_WGS_150/GRCh38/HG002_GRCh38_CMRG_SV_v1.00.bed --pass-ref ~/HG002_WGS_150/GRCh38/HG002_GRCh38_INS.vcf.gz --pass-query delly_ins.vcf.gz --min-size-ref 50 --slop 1000 --min-size-query 50 --pass-only
> Usage: svbench [OPTIONS] REFERENCE_VCF QUERY_VCFS...
> Try 'svbench --help' for help.
> 
> Error: No such option: --pass-ref Did you mean --pass-only?

Thanks.

**Comment by kcleal** [comment]
Hi @poddarharsh15,
Apologies, I have fixed the argument issue. Only `--pass-ref` and `--pass-query` are needed now. `--pass-only` has been removed.

**Comment by poddarharsh15** [comment]
Hello, @kcleal After installing the most recent version of svbench, I attempted to run it again, but I continue to receive the error message `TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'`
The issue, which I believe I may not have fully explained, is that I tried to benchmark DEL and INS separately in the.vcf files that I am using as truth sets from HG002(GIAB). However, when I separated the truth files and benched them, the.vcf file with just DEL SVTYPE was working well with the previous version and is now not working with the updated version. Benching them together, on the other hand, worked well.

**Comment by kcleal** [comment]
Hi @poddarharsh15,

No problem. Could you paste the full error message? Thanks!

**Comment by poddarharsh15** [comment]
Hi @kcleal please find the error below and could you please not remove --pass-only params in your new improvised code because I use it often while benchmarking, Thanks. 

`Score table caller=diploidSV_del.vcf.gz against dataset=REFERENCE
Scores:
                 Caller  T >=  Ref  Total  TP  FP  DTP  FN  Duplication  Precision  Recall      F1
0  diploidSV_del.vcf.gz  None   53     29  27   2    0  26          0.0      0.931  0.5094  0.6585
Traceback (most recent call last):
  File "/home/tigem/h.poddar/anaconda3/bin/svbench", line 33, in <module>
    sys.exit(load_entry_point('svbench', 'console_scripts', 'svbench')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/HG002_WGS_150/GRCh38/140528_D00360_0018_AH8VC6ADXX/bwamem/svbench/svbench/cli.py", line 38, in main
    svb.score(ref, query, allow_duplicate_tp=not no_duplicates)
  File "/home/tigem/h.poddar/HG002_WGS_150/GRCh38/140528_D00360_0018_AH8VC6ADXX/bwamem/svbench/svbench/quant_tools.py", line 54, in score
    quantify(targets[query.dataset], query, force_intersection, reciprocal_overlap, stratify=stratify,
  File "/home/tigem/h.poddar/HG002_WGS_150/GRCh38/140528_D00360_0018_AH8VC6ADXX/bwamem/svbench/svbench/io_tools.py", line 1782, in quantify
    s_fp, _ = np.histogram([i for i, j in zip(dat["svlen"], dat["TP"]) if i == i and not j], ref_size_bins)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/numpy/lib/histograms.py", line 867, in histogram
    sa = np.sort(a[i:i+BLOCK])
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tigem/h.poddar/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1017, in sort
    a.sort(axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
![Screenshot from 2024-06-05 11-09-21](https://github.com/kcleal/svbench/assets/45700858/ed966e95-4464-4f12-a1a3-2c011ceed391)
`

**Comment by kcleal** [comment]
Hi @poddarharsh15,
I belive it should be fixed now, and the --pass-only flag has been added back

**Comment by poddarharsh15** [comment]
Thanks again @kcleal I did install the newer version again before re-running the benchmark analysis and now it's fine :)

**Comment by kcleal** [comment]
Yes please clone the repo and install again. If it works then I can upload to pypi. Thanks!

**Comment by poddarharsh15** [comment]
It's working without any errors :+1:  Thanks!
